# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=50)),
                ('kuvaus', models.TextField(max_length=2500)),
                ('kuva', models.ImageField(upload_to='static/img/distrot')),
            ],
        ),
    ]
